### ISSUE TITLE
Need for 5th Sem 📚 

### ISSUE THREAD

**Issue by Sriansh-raj** [ShiwiDembla/ComputerScience_study-material#1]
Hi Shiwi, 
Actually I'm currently in 5th semester, so I was asking about whether you have any study materials for 5th semester ??

Pls provide, it will be a great help 😄

**Comment by ShiwiDembla** [comment]
Hey, for which subjects you need material? Can you mention them?

**Comment by Sriansh-raj** [comment]
> Hey, for which subjects you need material? Can you mention them?

I need materials for DAA(Design & Analysis of Algorithm), HPC(High Performance Computing) and CN(Computer Networks) if available.

Well I have got your mail, Thanks for that 😄.

Still if you can particularly help with these above mentioned subjects, then it will be a great help :D
